W6D1/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:new, :index]
end

W6D1/music/app/models/album.rb
class Album < ApplicationRecord
    validates :band_id, :title, :year, presence: true
    validates :live, inclusion: {in: [true, false]}

    belongs_to :band
end

W6D1/music/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums, dependent: :destroy
end

W6D1/music/app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true

    # Calls our method to ensure the user has a session token, or one is generated
    after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom.urlsafe_base64(16)
    end

    # Calls generate_session_token to create a new session token
    # Persists this user instance to the databse
    # Returns the new session token
    # Have to call 'self.session_token' instead of '@session_token' in order to
    # call self.save to add/update our database row with that user.
    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        return self.session_token
    end

    # Ensures that the user instance has a session_token
    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end
    
    # Creates a password digest and assigns it to the user instance
    # Also, creates an instance variable for @password 
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    # Creates a new instance of BCrypt Password with the value of the 
    # password_digest and calls is_password? to ensure the password the user
    # logged in with is equal to the password digest we have saved in the db 
    # for that user.
    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        if !user.nil? && user.is_password?(password)
            return user
        else
            return nil
        end
    end

end

W6D1/music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def new
        @band = Band.find(params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album)
        else
            flash.now[:error] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find(params[:id])
        render :edit
    end

    def update
        @album = Album.find(params[:id])
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:error] = @album.errors.full_messages
            render :edit
        end
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to band_url(@album)
    end

    private
    def album_params
        params.require(:album).permit(:band_id, :title, :year, :live)
    end
end

W6D1/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    # Checks if there is a current session token, if there is then we know
    # that the user is logged in.
    # Otherwise, return @current_user or find them by their session token
    def current_user
        return nil if !session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        @current_user.nil? ? false : true
    end

    def log_in_user!(user)
        token = user.reset_session_token!
        session[:session_token] = token
    end
end

W6D1/music/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band.id)
        else
            # render json: @band.errors.full_messages
            flash.now[:errors] = @band.errors.full_messages
            redirect_to :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end
    
    def show
        @band = Band.find(params[:id])
        render :show
    end

    def update
        @band = Band.find(params[:id])
        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:error] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    def index
        @bands = Band.all
        render :index
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

W6D1/music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # Render the sign in/sign up html page
    def new
        render :new
    end

    # Takes the username email and password and tries to generate a new session
    def create
        #gets the user
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        
        # if we found it, generate a new session token, change it on the user
        # instance as well as the cookie
        if !user.nil?
            log_in_user!(user)
            flash.now[:success] = "Login successful"
            redirect_to user_url(user)
        else
            flash.now[:error] = "Invalid email/password combo"
            redirect_to :new
        end
    end

    def destroy
        current_user.reset_session_token!
        session[:session_token] = nil

        redirect_to new_session_url
    end
end

W6D1/music/app/controllers/users_controller.rb
class UsersController < ApplicationController

    # Creates a new user instance and renders the 'new' view for the user to sign up
    def new
        @user = User.new
        render :new
    end

    # Saves that user
    # TODO: Users should be logged in immediately after they sign up
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Successfully created your account."
            redirect_to new_session_url
        else
            flash.now[:error] = @user.errors.full_messages
            render :new
        end 
    end

    def show
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W6D1/music/app/views/albums/edit.html.erb
<h2>Edit Album: <%= @album.title %> </h2>

<form action="<%= album_url(@album.id) %>" method="POST">

    <input type="hidden" name="_method" value="PATCH">

    <label for="new-album-band">Album title:</label>
    <input type="text" id="new-album-band" name="album[title]">

    <br>
    <label for="new-album-band">Band: </label>
    <select name="album[band_id]" id="new-album-band">
    <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= "selected" if @album.band_id == band.id %> >
        <%= band.name %>
        </option>
    <% end %>
    </select>


    <div>
        <label for="new-album-live">Live</label>
        <input type="radio" name="album[live]" value="t" id="new-album-live"
        <%= "checked" if @album.live %>>

        <label for="new-album-studio">Studio</label>
        <input type="radio" name="album[live]" value="f" id="new-album-studio"
        <%= "checked" if !@album.live %>>
    <div>

    <div>
        <label for='album-year'>Year</label>
        <input id='album-year' type="number" name="album[year]" value="<%= @album.year %>">
    </div>


    <input type="submit" value="Add">
        
</form>

W6D1/music/app/views/albums/new.html.erb
<h2>Add an album</h2>

<form action="<%= albums_url %>" method="POST">
    <label for="new-album-band">Album title:</label>
    <input type="text" id="new-album-band" name="album[title]">

    <br>
    <label for="new-album-band">Band: </label>
    <select name="album[band_id]" id="new-album-band">
    <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= "selected" if @album.band_id == band.id %> >
        <%= band.name %>
        </option>
    <% end %>
    </select>


    <div>
        <label for="new-album-live">Live</label>
        <input type="radio" name="album[live]" value="t" id="new-album-live"
        <%= "checked" if @album.live %>>

        <label for="new-album-studio">Studio</label>
        <input type="radio" name="album[live]" value="f" id="new-album-studio"
        <%= "checked" if !@album.live %>>
    <div>

    <div>
        <label for='album-year'>Year</label>
        <input id='album-year' type="number" name="album[year]" value="<%= @album.year %>">
    </div>


    <input type="submit" value="Add">
        
</form>
<br><br>
<a href="<%= band_url(@album.band_id) %>">Back to band</a>

W6D1/music/app/views/albums/show.html.erb
<h2> Album title: <%= @album.title %> </h2>
<h2> Band: <%= @album.band.name %> </h2>
<h2> Year: <%= @album.year %> </h2>
<h2> Live?: <%= @album.live %> </h2>

<a href="<%= edit_album_url(@album.id) %>">Edit this album</a>

W6D1/music/app/views/bands/edit.html.erb
<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">

    <label for="new-band">Edit Name</label>
    <input type="text" id="new-band" name="band[name]" value="<%= @band.name %>">
    <input type="submit" value="Edit Band">
</form>

W6D1/music/app/views/bands/index.html.erb
<p>All Bands</p>

<ul>
<% @bands.each do |band| %>
    <li>
        <a href="<%= band_url(band) %>"><%= band.name %></a>
    </li>
<% end %>
</ul>


<a href="<%= new_band_url %>">+Add a band</a>

W6D1/music/app/views/bands/new.html.erb
<form action="<%= bands_url %>" method="POST">
    <label for="new-band">Name</label>
    <input type="text" id="new-band" name="band[name]" value="<%= @band.name %>">
    <input type="submit" value="Add Band">
</form>

W6D1/music/app/views/bands/show.html.erb
<p>Band Name: <%= @band.name %></p>



<ul>
    <% if @band.albums.length > 0  %>
    <% @band.albums.each do |album| %>
    <li>
        <a href="<%= album_url(album.id) %>"><%= album.title %></a>
    </li>
    <% end %>
    <% end %>
</ul>

<form action="<%= band_url(@band.id) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this band">
</form>

<a href="<%= new_band_album_url(@band.id) %>">Add an album for this band</a>
<a href="<%= bands_url %>">Go back to all bands</a>

W6D1/music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Music App</h1>
    
    <%= flash[:success] %>
    <%= flash[:error] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

W6D1/music/app/views/users/new.html.erb
<div>
    <p>Create an account</p>
    <a href="<%= new_session_url %>">Already have an account? Sign in </a>
</div>

<form action="<%= users_url %>" method="POST">
    <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

    <label for="new-user-email">email</label>
    <input type="text" id="new-user-email" name="user[email]">

    <label for="new-user-password">password</label>
    <input type="password" id="new-user-password" name="user[password]">

    <input type="submit" value="Submit">
</form>

W6D1/music/app/views/users/show.html.erb
<p>User email: <%= current_user.email %> </p>